### ISSUE TITLE
Performance Analysis 

### ISSUE THREAD

**Issue by MaximumProgrammer** [GPUOpen-Effects/FidelityFX-FSR#10]
Hello did anyone some kind of performance analysis ? Just to check where to gain further performance !!!

Kind regards

**Comment by rys** [comment]
It's possible to profile the shader system and look at shader disassembly for the compiled shaders, if you want to go and look at performance in more detail and look for other opportunities yourself. We continued to look for performance optimisation opportunities at AMD as we keep working on it.

**Comment by MaximumProgrammer** [comment]
Thx i studied High Performance Computing so it would be a small project and cool to work on.
