### ISSUE TITLE
FSRSample_VK crashes in 5700.. but dx 12 is fine

### ISSUE THREAD

**Issue by gurachan** [GPUOpen-Effects/FidelityFX-FSR#12]

**Comment by rys** [comment]
@gurachan can you give me more details on the driver and operating system you're using with your 5700?

**Comment by gurachan** [comment]
ow i was at latest driver on that day xD also windows 11 ill try it again in windows 10 later

**Comment by gurachan** [comment]
i got it fix xD 
![image](https://user-images.githubusercontent.com/12135498/132117797-20fb6c13-8b0e-4b7a-80c8-2d90dfbed1d2.png)

the bandicam not even on xD but it somehow trying to load this also .. i rename the dll to something else now it opens weird xD but i guess i can close it...
