### ISSUE TITLE
Video Guide + Discord?

### ISSUE THREAD

**Issue by arctorin** [GPUOpen-Effects/FidelityFX-FSR#2]
1. Where can I find a descriptive, non-vague video guide for implementation?

2. Will there be a discord for support?

**Comment by rys** [comment]
We are looking at doing something like that, but I can't make any promises. As for a Discord for more real-time developer support, it's something we will discuss again internally later this year, but again, no promises.

**Comment by leonardus** [comment]
> 
> 
> We are looking at doing something like that, but I can't make any promises. As for a Discord for more real-time developer support, it's something we will discuss again internally later this year, but again, no promises.

I would prefer an IRC channel rather than Discord.

**Comment by dumbuz** [comment]
> I would prefer an IRC channel rather than Discord.

Not a lot of people use IRC for stuff like this. Discord seems like the more likely option.

**Comment by leonardus** [comment]
> 
> 
> > I would prefer an IRC channel rather than Discord.
> 
> Not a lot of people use IRC for stuff like this. Discord seems like the more likely option.

I disagree. Plenty of people use IRC to discuss graphics programming.

**Comment by AlexisTM** [comment]
Well, then let's make a Mumble server so everybody is mad :D

**Comment by Alistar031** [comment]
No, we can use it to make peace, and we need very strong support. Can you
support?

در تاریخ چهارشنبه ۲۱ ژوئیهٔ ۲۰۲۱،‏ ۱۳:۱۳ Alexis Paques <
***@***.***> نوشت:
