### ISSUE TITLE
[iGPU as FSR Renderer] AMD Advantage Program Laptops

### ISSUE THREAD

**Issue by RyzenAdvanced** [GPUOpen-Effects/FidelityFX-FSR#27]
Attn FSR Team,

Below Twitter video shares how iGPU could be utilized to boost FSR performance (10-25 FPS gain) by offloading FSR to iGPU and allowing dGPU handle the game code itself:
https://twitter.com/Rommex1/status/1442579419177144322

I wonder if this could becoming an official feature, as laptops such as AMD Advantage Program units (ASUS, MSI, Dell), where you have iGPU from AMD and dGPU from AMD, allowing iGPU handle FSR, could be indeed an interesting feature.

Share your thoughts please,

Thank you.

**Comment by rys** [comment]
Thanks for the suggestion, it's been noted. We're always thinking of ways to leverage the available hardware in a user's system to the best possible benefit, however unfortunately we can't comment on what's possible or what will or won't be implemented.
