### ISSUE TITLE
Just CMaked it, and by Building in Visual Studio 2019 in debug config will throw me an error saying "texture.cpp" file could not be found 

### ISSUE THREAD

**Issue by nunorelvao** [GPUOpen-Effects/FidelityFX-FSR#3]
![image](https://user-images.githubusercontent.com/2287697/125927694-41d72201-35a4-4ac6-8c59-1848df1069b1.png)

**Comment by nunorelvao** [comment]
I also tied to build it in "release" mode and no error occurs , but when launching nothing happens i can even capture a log, i am a developer, but not really used to Cmake and C++ compilation, more a C# dev, could the instructions maybe drill a bit more on how to proceed in order to actually have the demo running ? Thanks

**Comment by DevTechProfile** [comment]
You just have to include the source references. 
![image](https://user-images.githubusercontent.com/30285858/125930315-d820c700-9e33-440f-bdc2-0c3a69a61729.png)
![image](https://user-images.githubusercontent.com/30285858/125930365-3ae03609-b25f-45b6-89c1-1b6c38e9d6a9.png)

**Comment by sanyabeast** [comment]
Just installed all deps and regenerated solution. Everything seems OK :)
![image](https://user-images.githubusercontent.com/12017442/125930832-f751fe48-8cd9-4615-a481-9a63a9e1ad7c.png)

**Comment by nunorelvao** [comment]
Ok for

> Just installed all deps and regenerated solution. Everything seems OK :)
> ![image](https://user-images.githubusercontent.com/12017442/125930832-f751fe48-8cd9-4615-a481-9a63a9e1ad7c.png)

Ok , i also installed all deps , restarted system, not out of the box experience building it. Let me check with the reply of @DevTechProfile to include the source references.

**Comment by nunorelvao** [comment]
> You just have to include the source references.
> ![image](https://user-images.githubusercontent.com/30285858/125930466-33ceb324-246f-4018-887e-5a299e28ec16.png)
> ![image](https://user-images.githubusercontent.com/30285858/125930365-3ae03609-b25f-45b6-89c1-1b6c38e9d6a9.png)

Thanks for the quick reply @DevTechProfile , will try , not sure what i may have done wrong here but this thread can also help others who may face the same.

**Comment by nunorelvao** [comment]
Ok , confirmed its working as expected, had to clone again, seems by comparing previous folder with this new clone built at some point the "Cauldron-Media" folder of Cauldron SDK was not downloaded, and this was causing the issue indeed, Thanks for all the help , this is solved now!

![image](https://user-images.githubusercontent.com/2287697/125933097-fd013587-dea1-4e33-80e4-405770bc44c6.png)
