### ISSUE TITLE
DirectX Shader Compiler warning when disabling SAMPLE_SLOW_FALLBACK with VK FSR_Pass.hlsl shader

### ISSUE THREAD

**Issue by congyue1977** [GPUOpen-Effects/FidelityFX-FSR#7]
When the "SAMPLE_SLOW_FALLBACK " is disabled, The DirectX Shader Compiler shows the warning:

> Dxil Compile: EngineShaders/FSR_Pass.hlsl:63:37: warning: conversion from larger type 'vector<float, 4>' to smaller type 'float16_t4', possible loss of data [-Wconversion]
>                 AH4 FsrRcasLoadH(ASW2 p) { return InputTexture.Load(ASW3(ASW2(p), 0)); }

**Comment by rys** [comment]
Will be fixed in the next release, as mentioned on your associated PR. Thanks!
