### ISSUE TITLE
Strange noise

### ISSUE THREAD

**Issue by opinali** [GPUOpen-Effects/FidelityFX-FSR#9]
When I execute the FSRSample in my system (AMD RX 6800 XT Midnight Black), I hear a high-pitch noise apparently coming from the GPU. The noise changes as I rotate the scene or change options. I doesn't seem caused by fans, this doesn't happen running any game or other GPU-intensive program, including the Radeon app's GPU Stress Test. I am not crazy :) I can share a video that will show this behavior if necessary, the noise is low but very noticeable.

**Comment by Zorerk** [comment]
Hello opinali

What you describe sounds very much like Coil whine and is not directly caused by the software but issues with the hardware. You can see an example of this on the following video: 
[https://www.youtube.com/watch?v=HP73edpQwgc](url)

**Comment by Taxxor90** [comment]
On my 6800XT I'm getting like 1000+ FPS depending on the FSR mode, so it wouldn't be unusual if many GPUs start to have coil whine at these framerates

**Comment by opinali** [comment]
Thanks, this is exactly my problem, same noise. I guess the problem is that the demo code doesn't have any FPS capping? This looks dangerous, considering recent rumor about a prerelease game that's bricking some NVidia GPUs in similar circumstances (game running uncapped at thousands of fps in places like the menu).

**Comment by Taxxor90** [comment]
It has, you can turn on VSync at the bottom of the settings.

**Comment by opinali** [comment]
Uh that's true, had to scroll down to get the VSync option. I panicked with the noise before trying that. :) as a suggestion, perhaps VSync=on should be the default.
